# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true # make the workflow fail on high severity issues
confirm: true #  automatic confirmation of multiple file submissions (equivalent to --yes)

analyze:
  mode: deep
  async: true
  create-group: true
  group-name: "@lukso/lsp-smart-contracts"
  solc: 0.8.15
  remappings:
    - "@erc725/smart-contracts/=node_modules/@erc725/smart-contracts/"
    - "@openzeppelin/=node_modules/@openzeppelin/"
    - "solidity-bytes-utils/=node_modules/solidity-bytes-utils/"
  targets:
    # LSP1
    # ------------------
    - lsp1delegate/contract/LSP1UniversalReceiverDelegateUP.sol
    - lsp1delegate/contract/LSP1UniversalReceiverDelegateVault.sol

    # Standard version
    # ------------------
    - contracts/UniversalProfile.sol
    - contracts/LSP0ERC725Account/LSP0ERC725Account.sol
    - contracts/LSP6KeyManager/LSP6KeyManager.sol
    # - Tokens & NFTs
    - lsp4/contracts/LSP4DigitalAssetMetadata.sol
    - lsp7/contracts/LSP7DigitalAsset.sol
    - lsp7/contracts/presets/LSP7Mintable.sol
    - lsp7/contracts/extensions/LSP7Burnable.sol
    - lsp7/contracts/extensions/LSP7CappedSupply.sol
    - contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.sol
    - contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
    - contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.sol
    - contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.sol
    - contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.sol
    # - Vault & Social Recovery
    - lsp9/contracts/LSP9Vault.sol
    - contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecovery.sol

    # Proxy version
    # ------------------
    - contracts/UniversalProfileInit.sol
    - contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
    - lsp4/contracts/LSP4DigitalAssetMetadataInitAbstract.sol
    - contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
    # - Tokens & NFTs
    - lsp7/contracts/LSP7DigitalAssetInitAbstract.sol
    - lsp7/contracts/presets/LSP7MintableInit.sol
    - contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
    - contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInit.sol
    - contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupplyInitAbstract.sol
    - contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8EnumerableInitAbstract.sol
    # - Vault & Social Recovery
    - lsp9/contracts/LSP9VaultInit.sol
    - contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryInit.sol

    # Generic Modules & Factories
    # ------------------
    - contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
    - contracts/LSP16UniversalFactory/LSP16UniversalFactory.sol
    - contracts/LSP17ContractExtension/LSP17Extendable.sol
    - contracts/LSP17ContractExtension/LSP17Extension.sol
    - contracts/LSP20CallVerification/LSP20CallVerification.sol
