# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true # make the workflow fail on high severity issues
confirm: true #  automatic confirmation of multiple file submissions (equivalent to --yes)

analyze:
  mode: deep
  async: true
  create-group: true
  group-name: "@lukso/lsp-smart-contracts"
  solc: 0.8.15
  remappings:
    - "@erc725/smart-contracts/=node_modules/@erc725/smart-contracts/"
    - "@openzeppelin/=node_modules/@openzeppelin/"
    - "solidity-bytes-utils/=node_modules/solidity-bytes-utils/"
  targets:
    # LSP1
    # ------------------
    - @lukso/lsp1delegate-contracts/contract/LSP1UniversalReceiverDelegateUP.sol
    - @lukso/lsp1delegate-contracts/contract/LSP1UniversalReceiverDelegateVault.sol

    # Standard version
    # ------------------
    - @lukso/universalprofile-contracts/contracts/UniversalProfile.sol
    - @lukso/lsp0-contracts/contracts/LSP0ERC725Account.sol
    - @lukso/lsp6-contractscontracts/LSP6KeyManager.sol
    # - Tokens & NFTs
    - @lukso/lsp4-contracts/contracts/LSP4DigitalAssetMetadata.sol
    - @lukso/lsp7-contracts/contracts/LSP7DigitalAsset.sol
    - @lukso/lsp7-contracts/contracts/presets/LSP7Mintable.sol
    - @lukso/lsp7-contracts/contracts/extensions/LSP7Burnable.sol
    - @lukso/lsp7-contracts/contracts/extensions/LSP7CappedSupply.sol
    - @lukso/lsp8-contracts/contracts/presets/LSP8Mintable.sol
    - @lukso/lsp8-contracts/contracts/LSP8IdentifiableDigitalAsset.sol
    - @lukso/lsp8-contracts/contracts/extensions/LSP8Burnable.sol
    - @lukso/lsp8-contracts/contracts/extensions/LSP8CappedSupply.sol
    - @lukso/lsp8-contracts/contracts/extensions/LSP8Enumerable.sol
    # - Vault & Social Recovery
    - @lukso/lsp9-contracts/contracts/LSP9Vault.sol
    - contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecovery.sol

    # Proxy version
    # ------------------
    - @lukso/universalprofile-contracts/contracts/UniversalProfileInit.sol
    - @lukso/lsp0-contracts/contracts/LSP0ERC725AccountInit.sol
    - @lukso/lsp4-contracts/contracts/LSP4DigitalAssetMetadataInitAbstract.sol
    - @lukso/lsp6-contractscontracts/LSP6KeyManagerInit.sol
    # - Tokens & NFTs
    - @lukso/lsp7-contracts/contracts/LSP7DigitalAssetInitAbstract.sol
    - @lukso/lsp7-contracts/contracts/presets/LSP7MintableInit.sol
    - @lukso/lsp8-contracts/contracts/LSP8IdentifiableDigitalAssetInitAbstract.sol
    - @lukso/lsp8-contracts/contracts/presets/LSP8MintableInit.sol
    - @lukso/lsp8-contracts/contracts/extensions/LSP8CappedSupplyInitAbstract.sol
    - @lukso/lsp8-contracts/contracts/extensions/LSP8EnumerableInitAbstract.sol
    # - Vault @lukso/lsp8-contracts/& Recovery
    - @lukso/lsp9-contracts/contracts/LSP9VaultInit.sol
    - contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryInit.sol

    # Generic Modules & Factories
    # ------------------
    - @lukso/lsp14-contracts/contracts/LSP14Ownable2Step.sol
    - @lukso/lsp16-contracts/contracts/LSP16UniversalFactory.sol
    - @lukso/lsp17-contracts/contracts/LSP17Extendable.sol
    - @lukso/lsp17-contracts/contracts/LSP17Extension.sol
    - @lukso/lsp20-contracts/contracts/LSP20CallVerification.sol
