# This workflow benchmark the gas usage of Universal Profile for common interactions

name: 🆙 📊 Universal Profile Benchmark

on:
  # enable to run workflow manually
  workflow_dispatch:

  pull_request:
    types: [opened]

    # compare gas diff only when editing Solidity smart contract code
    paths:
      - "contracts/**/*.sol"

    # do not run on releases (merging to main)
    branches-ignore:
      - "main"

jobs:
  benchmark:
    # Do not run when preparing a release and the branch name contains the term "prepare"
    # (e.g: chore/prepare-release-x.x.x -> develop)
    if: ${{ !contains(github.ref, "release") }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js '16.15.0'
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build contract artifacts
        run: npm run build --if-present

      - name: 🧪 Run Benchmark tests
        run: npm run test:benchmark

      - name: 📊 Generate Benchmark Report
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: "./benchmark.md"
