# This workflow benchmark the gas usage of Universal Profile for common interactions

name: 🆙 📊 Universal Profile Benchmark

on:
  # enable to run workflow manually
  workflow_dispatch:

  pull_request:
    types: [opened]

    # compare gas diff only when editing Solidity smart contract code
    paths:
      - "contracts/**/*.sol"

    # do not run on releases (merging to main)
    branches-ignore:
      - "main"

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js '16.19.x'
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.x"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn

      - name: 🏗️ Build contract artifacts
        run: yarn build

      - name: 🧪 Run Benchmark tests
        run: yarn test:benchmark

      - name: 📊 Generate Benchmark Report
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: "./benchmark.md"
