# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI - Build + Lint + Test

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Solhint linter on smart Contracts
        run: npm run linter

      - name: Build contract artifacts
        run: npm run build --if-present

      - name: Generate typechain types
        run: npm run generate-types

      - run: ls -lhaG

      - name: cache dependencies + build
        uses: actions/cache@v2
        with:
          path: |
            node_modules 
            types
          key: ${{ github.run_id }}

      - run: ls -lahG
    
  test-UP:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        id: "build-cache"
        with:
          path: |
            node_modules 
            types
          key: ${{ github.run_id }}

      - run: ls -lahG

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: install dependencies
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: npm ci

      # - name: Use Node.js v16
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "16.x"
      #     cache: "npm"

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build contract artifacts
      #   run: npm run build --if-present

      # - name: Generate typechain types
      #   run: npm run generate-types

      - name: run Universal Profile tests
        run: npm run test:up

  test-LSP1:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules 
            types
          key: ${{ github.run_id }}

      - run: ls -lahG
      
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      # - name: Use Node.js v16
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "16.x"
      #     cache: "npm"

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build contract artifacts
      #   run: npm run build --if-present

      # - name: Generate typechain types
      #   run: npm run generate-types

      - name: run LSP1 tests
        run: npm run test:lsp1
