# This workflow builds Android and iOS SDK artifacts
name: Build Artifacts

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if version changed
        uses: EndBug/version-check@v1
        id: check

      - name: Use Node.js '16.15.0'
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # Android artifacts
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Web3j
        run: curl -L get.web3j.io | sh && source $HOME/.web3j/source.sh

      - name: Generate Smart Contracts ABI + Binaries
        run: npx ts-node ./scripts/ci/android-artifacts.ts

      - name: Generate Java wrappers
        run: ./scripts/ci/generate-java-wrapper.sh

      - name: Build jar
        working-directory: ./scripts/java
        run: |
          chmod +x build.gradle
          gradle build

      # iOS artifacts
      - name: Generate iOS artifacts
        run: |
          mkdir ios
          npx ts-node ./scripts/ci/ios-artifacts.ts

      # Upload Artifacts
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && steps.check.outputs.changed == 'true'
        with:
          name: UPContractsAbi.swift
          path: ios/UPContractsAbi.swift

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2
        if: github.event_name == 'push'  && steps.check.outputs.changed == 'true'
        with:
          name: upcontracts.jar
          path: java/build/libs/upcontracts.jar

      # Trigger Release
      - name: Repository Dispatch
        if: github.event_name == 'push' && steps.check.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
