# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI - Build + Lint + Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      - name: Use Node.js '16.19.x'
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.x"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn

      - name: 🔍 Run Solidity Linter
        run: yarn linter

      - name: 🎨 Check Prettier Style
        run: yarn format:check

      # This will also generate the Typechain types used by the Chai tests
      - name: 🏗️ Build contract artifacts
        run: |
          yarn build
          yarn build:js
          yarn pack
          tar tfz package.tgz

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./package.tgz

      - name: 📤 cache dependencies + build
        uses: actions/cache/save@v3
        with:
          path: |
            artifacts
            node_modules
            types
            contracts.ts
            .yarn/install-state.gz
          key: lint-${{ github.run_id }}

  test-suites:
    strategy:
      matrix:
        lsp:
          [
            "up",
            "upinit",
            "lsp1",
            "lsp2",
            "lsp4",
            "lsp6",
            "lsp6init",
            "lsp7",
            "lsp7init",
            "lsp8",
            "lsp8init",
            "lsp9",
            "lsp9init",
            "lsp11",
            "lsp11init",
            "lsp20",
            "lsp20init",
            "universalfactory",
            "reentrancy",
            "reentrancyinit",
            "mocks",
          ]

    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: 📥 restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            artifacts
            node_modules
            types
            contracts.ts
            .yarn/install-state.gz
          key: lint-${{ github.run_id }}

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: 🧪 run tests
        run: yarn test:${{ matrix.lsp }}
