name: Build Artifacts

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if version changed
        uses: EndBug/version-check@v2
        id: check

      - name: Use Node.js '16.15.0'
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # Trigger Release
      - name: Repository Dispatch
        if: github.event_name == 'push' && steps.check.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
