# This workflow runs the tests with code coverage to analyze how much
# Solidity code in the smart contracts is covered by the tests.
# It then submit the code coverage report to coveralls.io.

name: Solidity Code coverage

on:
  push:
    branches:
      - "develop"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install dependencies
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn

      # This will also generate the Typechain types used by the Chai tests
      - name: Build contract artifacts
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
