# This workflow runs the tests with code coverage to analyze how much
# Solidity code in the smart contracts is covered by the tests.
# It then submit the code coverage report to coveralls.io.

name: Solidity Code coverage

on:
  pull_request:
    branches:
      - "develop"
    types:
      - closed

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: npm ci

      # This will also generate the Typechain types used by the Chai tests
      - name: Build contract artifacts
        run: npx hardhat compile

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
