# This workflow deploys + verify the base smart contracts on the LUKSO Mainnet chain
name: Deploy + Verify on Mainnet

env:
  CONTRACT_VERIFICATION_MAINNET_PK: ${{ secrets.CONTRACT_VERIFICATION_MAINNET_PK }}
  DEPLOYER_ADDRESS: "0xF0efeD8d49c0FA6CFC861Bf0311b6B3a4414e4b7"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build contract artifacts
        run: npm run build

      - name: Verify Deployer Balance
        run: npx hardhat verify-balance --network luksoMainnet

      - name: Deploy base contracts on mainnet
        run: npx hardhat deploy --network luksoMainnet --tags base --reset

      # Loop through deployment files and recover address of deployed contracts to verify
      - name: Verify deployed contracts on mainnet
        run: sh ./scripts/ci/verify-base-contracts-mainnet.sh
