# This workflow checks for Smart Contract security and vulnerabilities by submitting to Mythx
# Inspired from: https://github.com/Uniswap/v3-core/blob/main/.github/workflows/mythx.yml
name: Mythx

on:
  workflow_dispatch:

jobs: 
  mythx:
    name: Submit to Mythx
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "npm"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install node dependencies (including submodules)
        run: git submodule update --init --recursive
        run: npm ci
        run: cd ./submodules/ERC725/implementations && npm install

      - name: Install pip3
        run: python -m pip install --upgrade pip

      - name: Install mythx CLI
        run: pip3 install mythx-cli

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Install solc 0.8.7
        run: |
          solc-select install 0.8.7
          solc-select use 0.8.7

      - name: Submit code to Mythx
        # Submit code to Mythx