# This workflow publishes Android artifacts
# See: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
name: Upload Android Github artifacts CD

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  android-build-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-artifacts.yml
          workflow_conclusion: success
          name: upcontracts.jar
          path: scripts/build/libs
          branch: main
          event: push

      - name: Publish to Maven
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        working-directory: ./scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
