# This workflow build and publish NPM artifacts
name: Publish NPM artifacts

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  publish-npm-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js '16.19.x'
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@lukso"
          cache: "yarn"

      - name: Install
        run: |
          yarn

      # This will also generate the Typechain types used by the Chai tests
      - name: Build and Test
        run: |
          yarn build
          yarn test

      - name: Publish
        run: |
          yarn build:js
          yarn package
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
