# This workflow publishes Android artifacts to Github Packages
# See: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages
name: Upload Android GitHub artifacts

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  publish-android-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Download Android artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-artifacts.yml
          workflow_conclusion: success
          name: lspsmartcontracts.jar
          path: scripts/build/libs
          branch: main
          event: push

      - name: Publish to Github Packages
        working-directory: ./scripts/java
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
